package(
    default_visibility = ["//visibility:public"],
    licenses = ["notice"],
)

# Libraries
# =========

py_library(
    name = "beam",
    srcs = ["__init__.py"],
    srcs_version = "PY3",
    deps = [":csv"],
)

py_library(
    name = "csv",
    srcs = ["csv.py"],
    srcs_version = "PY3",
    deps = [],
)
