package(
    default_visibility = ["//visibility:public"],
    licenses = ["notice"],
)

# All test data
# =============

py_library(
    name = "test_data",
    srcs = ["__init__.py"],
    srcs_version = "PY3",
)

# Individual test data
# =====================

py_library(
    name = "correct_lag",
    srcs = ["correct_lag.py"],
    srcs_version = "PY3",
    deps = [
        # pandas dep,
    ],
)
