package(
    default_visibility = ["//visibility:public"],
    licenses = ["notice"],
)

# Libraries
# =========

py_test(
    name = "check_install_test",
    srcs = ["check_install_test.py"],
    srcs_version = "PY3",
    deps = [
        "//tools:check_install",
    ],
)
