package(
    default_visibility = ["//visibility:public"],
    licenses = ["notice"],
)

# Libraries
# =========

py_library(
    name = "data",
    srcs = ["__init__.py"],
    srcs_version = "PY3",
    deps = [
        ":event",
    ],
)

py_library(
    name = "event",
    srcs = ["event.py"],
    srcs_version = "PY3",
)
