package(
    default_visibility = ["//visibility:public"],
    licenses = ["notice"],
)

# Libraries
# =========

py_library(
    name = "duration",
    srcs = ["duration.py"],
    srcs_version = "PY3",
    deps=[
        "//temporian/core/data:duration",
        "//temporian/core/data:duration_utils",
        ],
)
