package(
    default_visibility = ["//visibility:public"],
    licenses = ["notice"],
)

# Libraries
# =========

py_library(
    name = "dict",
    srcs = ["dict.py"],
    srcs_version = "PY3",
    deps = [
        # already_there/apache_beam
        # already_there/numpy
        "//temporian/implementation/numpy/data:event_set",
        "//temporian/core/data:dtype",
        "//temporian/core/data:node",
    ],
)

py_library(
    name = "csv",
    srcs = ["csv.py"],
    srcs_version = "PY3",
    deps = [
        # already_there/apache_beam
        # already_there/numpy
        "//temporian/implementation/numpy/data:event_set",
        "//temporian/core/data:dtype",
        "//temporian/core/data:node",
    ],
)

py_library(
    name = "tensorflow",
    srcs = ["tensorflow.py"],
    srcs_version = "PY3",
    deps = [
        # already_there/apache_beam
        # already_there/numpy
        "//temporian/implementation/numpy/data:event_set",
        "//temporian/core/data:dtype",
        "//temporian/core/data:node",
    ],
)
