
package(
    default_visibility = ["//visibility:public"],
    licenses = ["notice"],
)

# Libraries
# =========

py_library(
    name = "implementation",
    srcs = ["__init__.py"],
    srcs_version = "PY3",
)
