# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporian/proto/core.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1atemporian/proto/core.proto\x12\x0ftemporian.proto"\x98\x02\n\tProcessor\x12,\n\toperators\x18\x01'
    b" \x03(\x0b\x32\x19.temporian.proto.Operator\x12&\n\x06\x65vents\x18\x02"
    b" \x03(\x0b\x32\x16.temporian.proto.Event\x12*\n\x08\x66\x65\x61tures\x18\x03"
    b" \x03(\x0b\x32\x18.temporian.proto.Feature\x12,\n\tsamplings\x18\x04"
    b" \x03(\x0b\x32\x19.temporian.proto.Sampling\x12,\n\x06inputs\x18\x05"
    b" \x03(\x0b\x32\x1c.temporian.proto.IOSignature\x12-\n\x07outputs\x18\x06"
    b' \x03(\x0b\x32\x1c.temporian.proto.IOSignature",\n\x0bIOSignature\x12\x0b\n\x03key\x18\x01'
    b" \x01(\t\x12\x10\n\x08\x65vent_id\x18\x02"
    b' \x01(\t"\xe7\x02\n\x08Operator\x12\n\n\x02id\x18\x01'
    b" \x01(\t\x12\x18\n\x10operator_def_key\x18\x02"
    b" \x01(\t\x12\x37\n\x06inputs\x18\x03"
    b" \x03(\x0b\x32'.temporian.proto.Operator.EventArgument\x12\x38\n\x07outputs\x18\x04"
    b" \x03(\x0b\x32'.temporian.proto.Operator.EventArgument\x12\x37\n\nattributes\x18\x05"
    b" \x03(\x0b\x32#.temporian.proto.Operator.Attribute\x1a.\n\rEventArgument\x12\x0b\n\x03key\x18\x01"
    b" \x01(\t\x12\x10\n\x08\x65vent_id\x18\x02"
    b" \x01(\t\x1aY\n\tAttribute\x12\x0b\n\x03key\x18\x01"
    b" \x01(\t\x12\x14\n\ninteger_64\x18\x02"
    b" \x01(\x03H\x00\x12\r\n\x03str\x18\x03"
    b" \x01(\tH\x00\x12\x12\n\x08\x66loat_64\x18\x04"
    b' \x01(\x01H\x00\x42\x06\n\x04type"h\n\x05\x45vent\x12\n\n\x02id\x18\x01'
    b" \x01(\t\x12\x13\n\x0bsampling_id\x18\x02"
    b" \x01(\t\x12\x13\n\x0b\x66\x65\x61ture_ids\x18\x03"
    b" \x03(\t\x12\x0c\n\x04name\x18\x04"
    b" \x01(\t\x12\x1b\n\x13\x63reator_operator_id\x18\x05"
    b' \x01(\t"\xcc\x01\n\x07\x46\x65\x61ture\x12\n\n\x02id\x18\x01'
    b" \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12-\n\x05\x64type\x18\x03"
    b" \x01(\x0e\x32\x1e.temporian.proto.Feature.DType\x12\x13\n\x0bsampling_id\x18\x04"
    b" \x01(\t\x12\x1b\n\x13\x63reator_operator_id\x18\x05"
    b' \x01(\t"F\n\x05\x44Type\x12\r\n\tUNDEFINED\x10\x00\x12\x0b\n\x07\x46LOAT64\x10\x01\x12\t\n\x05INT64\x10\x02\x12\x0b\n\x07\x46LOAT32\x10\x03\x12\t\n\x05INT32\x10\x04"B\n\x08Sampling\x12\n\n\x02id\x18\x01'
    b" \x01(\t\x12\r\n\x05index\x18\x02"
    b" \x03(\t\x12\x1b\n\x13\x63reator_operator_id\x18\x03"
    b' \x01(\t"\xc3\x03\n\x0bOperatorDef\x12\x0b\n\x03key\x18\x01'
    b" \x01(\t\x12\x32\n\x06inputs\x18\x02"
    b' \x03(\x0b\x32".temporian.proto.OperatorDef.Input\x12\x34\n\x07outputs\x18\x03'
    b" \x03(\x0b\x32#.temporian.proto.OperatorDef.Output\x12:\n\nattributes\x18\x04"
    b" \x03(\x0b\x32&.temporian.proto.OperatorDef.Attribute\x1a)\n\x05Input\x12\x0b\n\x03key\x18\x01"
    b" \x01(\t\x12\x13\n\x0bis_optional\x18\x03"
    b" \x01(\x08\x1a\x15\n\x06Output\x12\x0b\n\x03key\x18\x01"
    b" \x01(\t\x1a\xbe\x01\n\tAttribute\x12\x0b\n\x03key\x18\x01"
    b" \x01(\t\x12\x39\n\x04type\x18\x02"
    b" \x01(\x0e\x32+.temporian.proto.OperatorDef.Attribute.Type\x12\x13\n\x0bis_optional\x18\x03"
    b' \x01(\x08"T\n\x04Type\x12\r\n\tUNDEFINED\x10\x00\x12\x0e\n\nINTEGER_64\x10\x01\x12\n\n\x06STRING\x10\x02\x12\x13\n\x0fREPEATED_STRING\x10\x03\x12\x0c\n\x08\x46LOAT_64\x10\x04'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "temporian.proto.core_pb2", globals()
)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _PROCESSOR._serialized_start = 48
    _PROCESSOR._serialized_end = 328
    _IOSIGNATURE._serialized_start = 330
    _IOSIGNATURE._serialized_end = 374
    _OPERATOR._serialized_start = 377
    _OPERATOR._serialized_end = 736
    _OPERATOR_EVENTARGUMENT._serialized_start = 599
    _OPERATOR_EVENTARGUMENT._serialized_end = 645
    _OPERATOR_ATTRIBUTE._serialized_start = 647
    _OPERATOR_ATTRIBUTE._serialized_end = 736
    _EVENT._serialized_start = 738
    _EVENT._serialized_end = 842
    _FEATURE._serialized_start = 845
    _FEATURE._serialized_end = 1049
    _FEATURE_DTYPE._serialized_start = 979
    _FEATURE_DTYPE._serialized_end = 1049
    _SAMPLING._serialized_start = 1051
    _SAMPLING._serialized_end = 1117
    _OPERATORDEF._serialized_start = 1120
    _OPERATORDEF._serialized_end = 1571
    _OPERATORDEF_INPUT._serialized_start = 1314
    _OPERATORDEF_INPUT._serialized_end = 1355
    _OPERATORDEF_OUTPUT._serialized_start = 1357
    _OPERATORDEF_OUTPUT._serialized_end = 1378
    _OPERATORDEF_ATTRIBUTE._serialized_start = 1381
    _OPERATORDEF_ATTRIBUTE._serialized_end = 1571
    _OPERATORDEF_ATTRIBUTE_TYPE._serialized_start = 1487
    _OPERATORDEF_ATTRIBUTE_TYPE._serialized_end = 1571
# @@protoc_insertion_point(module_scope)
