package(
    default_visibility = ["//visibility:public"],
    licenses = ["notice"],
)

# Tests
# =====

py_test(
    name = "csv_test",
    srcs = ["csv_test.py"],
    srcs_version = "PY3",
    deps = [
        "//temporian/beam",
    ],
    data = ["//temporian/test/test_data"],
)
