package(
    default_visibility = ["//visibility:public"],
    licenses = ["notice"],
)

py_binary(
    name = "m5_competition",
    srcs = ["m5_competition.py"],
    srcs_version = "PY3",
    deps = ["//temporian"],
)
