load("//temporal_feature_processor/utils:compile.bzl", "all_proto_library")

package(
    default_visibility = ["//visibility:public"],
    licenses = ["notice"],
)

# Proto
# ========

all_proto_library(
    name = "core_proto",
    srcs = ["core.proto"],
    deps = [],
)
