package(
    default_visibility = ["//visibility:public"],
    licenses = ["notice"],
)

# Tests
# =====
py_test(
    name = "test_sampling",
    srcs = ["test_sampling.py"],
    srcs_version = "PY3",
    deps = [
        "//temporian/implementation/pandas/data:sampling",
    ],
)
