package(
    default_visibility = ["//visibility:public"],
    licenses = ["notice"],
)

# Tests
# =========

py_test(
    name = "string_test",
    srcs = ["string_test.py"],
    srcs_version = "PY3",
    deps = ["//temporian/utils:string"],
)
