package(
    default_visibility = ["//visibility:public"],
    licenses = ["notice"],
)

# Libraries
# =========

py_library(
    name = "check_install",
    srcs = ["check_install.py"],
    srcs_version = "PY3",
    deps = [
        "//temporian",
    ],
)
