package(
    default_visibility = ["//visibility:public"],
    licenses = ["notice"],
)

# All test data
# =============

py_library(
    name = "test_data",
    srcs = ["__init__.py"],
    srcs_version = "PY3",
)

# Individual test data
# =====================

py_library(
    name = "correct_sum",
    srcs = ["correct_sum.py"],
    srcs_version = "PY3",
    deps = [
        # pandas dep,
    ],
)

py_library(
    name = "different_timestamps",
    srcs = ["different_timestamps.py"],
    srcs_version = "PY3",
    deps = [
        # pandas dep,
    ],
)

py_library(
    name = "different_indexes",
    srcs = ["different_indexes.py"],
    srcs_version = "PY3",
    deps = [
        # pandas dep,
    ],
)

py_library(
    name = "sum_with_nan",
    srcs = ["sum_with_nan.py"],
    srcs_version = "PY3",
    deps = [
        # pandas dep,
    ],
)
